---
- hosts: portfolio_server
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest portfolio image
      community.docker.docker_image:
        name: zainab0405/zainab-portfolio:latest
        source: pull
        force_source: yes

    - name: Stop old container
      community.docker.docker_container:
        name: portfolio
        state: absent

    - name: Run portfolio container
      community.docker.docker_container:
        name: portfolio
        image: zainab0405/zainab-portfolio:latest
        ports:
          - "80:80"
        restart_policy: always
        state: started
